module.exports={
    ADMIN_COLLECTION:'admin',
    OWNER_COLLECTION:'owner',
    SCREEN_COLLECTION:'screen',
    MOVIE_COLLECTION:'movie',
    SHOW_COLLECTION:'show',
    UPCOMINGMOVIES_COLLECTION:'upcomingmovies',
    USER_COLLECTION:'user',
    SEAT_COLLECTION:"seat",
    CHECKOUT_COLLECTION:"checkout"
}